---

- name: Ensure Ansible dependencies are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - libsemanage-python
    - libselinux-python
    - policycoreutils-python


- name: Ensure basic tools are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - vim
    - htop
    - git
